### ISSUE TITLE
Request support for tesseract4 beta for zesty

### ISSUE THREAD

**Issue by Shreeshrii** [AlexanderP/tesseract-debian#4]
Please see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/xvpvX8GeNv4/MqOYgC4eAAAJ

Even though officially Zesty may be at EOL, there may be many users on that platform. It will be helpful to have latest ppa available for it, if possible.

Thanks.

**Comment by AlexanderP** [comment]
In ppа under zesty it is impossible to collect.
Exit here is just my build.

**Comment by Shreeshrii** [comment]
Thanks. Closing the issue.

**Comment by AlexanderP** [comment]
I added packages for Ubuntu Zesty in https://notesalexp.org/tesseract-ocr/

**Comment by Shreeshrii** [comment]
Thank you. Appreciate your prompt response.

I have added link to wiki.

Please check that the listings under the following link are OK.

https://github.com/tesseract-ocr/tesseract/wiki#tesseract-400-beta-1-packages-with-lstm-engine-and-related-traineddata

**Comment by AlexanderP** [comment]
ok

**_rpm package_**

**For CentOS 7 run the following as root:**
```
yum-config-manager --add-repo https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/CentOS_7/
yum update
yum install tesseract 
yum install tesseract-langpack-deu
```

**For Scientific Linux 7  run the following as root:**
```
yum-config-manager --add-repo https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/ScientificLinux_7/
yum update
yum install tesseract 
yum install tesseract-langpack-deu
```

**For Fedora 27 run the following as root:**
```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/Fedora_27/home:Alexander_Pozdnyakov.repo
dnf install tesseract
dnf install tesseract-langpack-deu
```
**For Fedora 26 run the following as root:**
```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/Fedora_26/home:Alexander_Pozdnyakov.repo
dnf install tesseract
dnf install tesseract-langpack-deu
```

**For Fedora 25 run the following as root:**
```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/Fedora_25/home:Alexander_Pozdnyakov.repo
dnf install tesseract
dnf install tesseract-langpack-deu
```

**For openSUSE Tumbleweed run the following as root:**
```
zypper addrepo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/openSUSE_Tumbleweed/home:Alexander_Pozdnyakov.repo
zypper refresh
zypper install tesseract-ocr
zypper install tesseract-ocr-traineddata-german
```


**For openSUSE Leap 42.3 run the following as root:**
```
zypper addrepo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/openSUSE_Leap_42.3/home:Alexander_Pozdnyakov.repo
zypper refresh
zypper install tesseract-ocr
zypper install tesseract-ocr-traineddata-german
```

**For openSUSE Leap 15.0 run the following as root:**
```
zypper addrepo https://download.opensuse.org/repositories/home:Alexander_Pozdnyakov/openSUSE_Leap_15.0/home:Alexander_Pozdnyakov.repo
zypper refresh
zypper install tesseract-ocr
zypper install tesseract-ocr-traineddata-german
```

**Comment by Shreeshrii** [comment]
Thank you. I have added it to the wiki.
